FROM ruby:2.6.5

WORKDIR /work

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN apt clean

COPY Gemfile .
COPY bin/bundle bin/bundle
RUN bin/bundle install --path vendor/cache
