version: '3.7'

services:

  web:
    image: bravo-todo
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_list
